/*
 Date & Time Function 
 1. GETDATE()  , getdate(),   CURRENT_TIMESTAMP(),   SYSDATETIME() = current Time
 2. DATENAME()  = Name Of Month
 3. DATEDIFF() = Range,   Calculate age 
 4. DATEADD()  = ADD ON DATE.
*/

SELECT GETDATE()  AS 'CURRENT_DATE AND TIME'
SELECT SYSDATETIME()
SELECT CURRENT_TIMESTAMP

SELECT DATENAME(MONTH,CURRENT_TIMESTAMP);
SELECT DATENAME(YEAR,CURRENT_TIMESTAMP);
SELECT DATENAME(HOUR,CURRENT_TIMESTAMP);

SELECT DATEDIFF(YEAR,'DECEMBER 02 2001',CURRENT_TIMESTAMP);
SELECT DATEDIFF(MONTH,'DECEMBER 02 2001',CURRENT_TIMESTAMP);

SELECT DATEADD(YEAR,100,CURRENT_TIMESTAMP);